# Переменные компилятора
CXX = g++
CXXFLAGS = -std=c++20 -Wall -Wextra -Werror
LDFLAGS = -lgtest -lgtest_main -pthread

# Исходные файлы
MAIN_SRC = main.cpp
TEST_SRC = test.cpp
APP_OBJS = main.o

# Исполняемые файлы
MAIN_APP = student_app
TEST_RUNNER = test_runner

.PHONY: all clean test

# Цель по умолчанию: собрать основное приложение
all: $(MAIN_APP)

# Сборка основного приложения
$(MAIN_APP): $(MAIN_SRC)
	$(CXX) $(CXXFLAGS) $(MAIN_SRC) -o $(MAIN_APP)

# Сборка и запуск тестов
test: $(TEST_RUNNER)
	./$(TEST_RUNNER)

# Сборка исполняемого файла тестов
# Теперь он зависит от test.cpp и main.cpp (скомпилированных в .o)
$(TEST_RUNNER): $(TEST_SRC) $(MAIN_SRC)
	$(CXX) $(CXXFLAGS) $(TEST_SRC) $(MAIN_SRC) -o $(TEST_RUNNER) $(LDFLAGS)

# Очистка
clean:
	rm -f $(MAIN_APP) $(TEST_RUNNER) *.o
