# Makefile:

.PHONY: all app test clean

# Цель по умолчанию: собрать основное приложение
all: app

# Цель для сборки основного приложения (student_app)
# Просто берет main.cpp и database.cpp и создает из них student_app
app:
	g++ -std=c++20 -Wall -Wextra -o student_app main.cpp database.cpp

# Цель для сборки И ЗАПУСКА тестов (именно ее вызывает GitHub Actions)
# Шаг 1: Компилирует test.cpp и database.cpp, линкует с gtest и создает test_runner
# Шаг 2: Сразу же запускает созданный test_runner
test:
	g++ -std=c++20 -Wall -Wextra --coverage -o test_runner test.cpp database.cpp -lgtest -lgtest_main -pthread
	./test_runner

# Цель для очистки
clean:
	rm -f student_app test_runner *.gcno *.gcda

