# Переменные компилятора
CXX = g++
# Добавляем --coverage для будущего бейджа покрытия
CXXFLAGS = -std=c++20 -Wall -Wextra -I. --coverage
# Флаги для линковки с GoogleTest
LDFLAGS = -lgtest -lgtest_main -pthread --coverage

# Исходники и объекты
DATABASE_SRC = database.cpp
DATABASE_OBJ = $(DATABASE_SRC:.cpp=.o)

MAIN_SRC = main.cpp
MAIN_OBJ = $(MAIN_SRC:.cpp=.o)

TEST_SRC = test.cpp
TEST_OBJ = $(TEST_SRC:.cpp=.o)

# Исполняемые файлы
MAIN_APP = student_app
TEST_RUNNER = test_runner

# .PHONY указывает цели, которые не являются файлами
.PHONY: all clean test

# Цель по умолчанию: собрать основное приложение и тесты
all: $(MAIN_APP) $(TEST_RUNNER)

# Правило для сборки основного приложения
$(MAIN_APP): $(MAIN_OBJ) $(DATABASE_OBJ)
	$(CXX) $(CXXFLAGS) -o $@ $^

# Правило для сборки тестов
$(TEST_RUNNER): $(TEST_OBJ) $(DATABASE_OBJ)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

# Цель для запуска тестов
test: $(TEST_RUNNER)
	./$(TEST_RUNNER)

# Правило для компиляции .cpp в .o (объектные файлы)
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c -o $@ $<

# Очистка скомпилированных файлов
clean:
	rm -f $(MAIN_APP) $(TEST_RUNNER) *.o *.gcno *.gcda
