name: C/C++ CI

on:
  push:
    branches: [ "main" ] # Можете заменить "main" на "master" в зависимости от имени вашей основной ветки
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtest-dev cmake

    - name: Build GoogleTest
      # GoogleTest нужно скомпилировать перед использованием
      run: |
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo mv lib/libgtest* /usr/lib/

    - name: Build application and tests
      run: make test

    - name: Run tests
      run: ./test_runner
