name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtest-dev cmake

    - name: Build and install GoogleTest properly
      run: |
        cd /usr/src/gtest
        sudo mkdir -p build && cd build
        sudo cmake ..
        sudo make
        sudo make install
        # Или альтернативно:
        # sudo cp lib/libgtest*.a /usr/lib/

    - name: Build application and tests
      run: make test

    - name: Run tests
      run: ./test_runner
