name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtest-dev cmake

    - name: Build GoogleTest
      run: |
        cd /usr/src/googletest
        sudo mkdir -p build && cd build
        sudo cmake ..
        sudo make
        sudo cp lib/libgtest*.a /usr/lib/

    - name: Debug Makefile
      run: |
        echo "=== Makefile content ==="
        cat Makefile
        echo "=== Available targets ==="
        make -qp | grep -E '^[a-zA-Z_][a-zA-Z0-9_]*:' | head -10

    - name: Build and test
      run: make run-tests
